# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Jayanth Karthikeyan
title: Graduate Mechanical Engineer 
email: ijk@asu.edu
website: https://github.com/jaykarthi

# Social links
twitter_username: JayanthKarthi
github_username:  jaykarthi
instagram_username: jayanth_karthikeyan
linkedin_username: jayanthkarthikeyan

# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/jay3.jpg
about_content: | # this will include new lines to allow paragraphs
 Creative and Autonomous, Graduate Mechanical Engineer with over three years of experience in programming, leadership, product design and development, with Six Sigma Green Belt Certification who is excited about designing products used by millions and making positive impact looking for full time Mechanical/Product Design Engineering positions.

  Technical Skills: <mark> Mechanical Product Design </mark> and <mark> Robotics </mark> and <mark> Computer Vision </mark> and <mark> Path Planning </mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: AWARDS & RECOGNITION
more_content: | # this will include new lines to allow paragraphs


# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
